version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - FAISS_URI=${FAISS_URI:-gs://unstructured-intel-dev/faiss/}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Local MinIO for testing GCS locally
  minio:
    image: minio/minio:RELEASE.2024-01-31T20-20-33Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
